[project]
name = "dtuhpc"
description = "Python package for interfacing with DTU's HPC cluster"
version = "0.1.0-beta"
authors = [
    { name = "Jonas Hoffmann", email = "jonashoffmanns@gmail.com" }
]
readme = {file = ["README"], content-type = "text/markdown"}
license = {file = ["LICENSE"]}

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages]
find = {}