[project]
name = "dtuhpc"
description = "Python package for interfacing with DTU's HPC cluster"
version = "0.1.0"
authors = [
    { name = "Jonas Hoffmann", email = "jonashoffmanns@gmail.com" }
]
dependencies = [
    "paramiko"
]

[project.optional-dependencies]
dev = [
    "tox",
    "pre-commit",
    "black",
    "isort",
    "flake8"
]
tests = [
    "pytest",
    "pytest-cov"
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages]
find = {}