queue = "hpc"
name = "test"
walltime = { hours = 0, minutes = 15 }
single_host = true
cpu = 2
memory = 4
standard_output = "test.out"
error_output = "test.err"

commands = [
    "echo 'Hello World!' > hello.txt",
]
