name: "Check version has been bumped"

on:
  pull_request:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test if version has been bumped
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files in the docs folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            VERSION

      - name: Run step if any file(s) in the docs folder change
        if: steps.changed-files-specific.outputs.any_changed == 'false'
        run: |
          echo "No version bump detected"
          exit 1
